💚 Ci: add input validation

diff --git a/.github/workflows/conferenceapp.yaml b/.github/workflows/conferenceapp.yaml
--- a/.github/workflows/conferenceapp.yaml
+++ b/.github/workflows/conferenceapp.yaml
@@ -34,6 +34,29 @@ on:
 
 jobs:
 
+  validate-inputs:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate Inputs
+        run: |
+          if [[ "${{ github.event.inputs['release-type'] }}" == "build" ]]; then
+            if [[ -z "${{ github.event.inputs['build-version'] }}" ]]; then
+              echo "Error: build-version is required for a build release."
+              exit 1
+            fi
+            if [[ -z "${{ github.event.inputs['build-number'] }}" ]]; then
+              echo "Error: build-number is required for a build release."
+              exit 1
+            fi
+            if [[ -z "${{ github.event.inputs['changelog'] }}" ]]; then
+              echo "Error: changelog is required for a build release."
+              exit 1
+            fi
+          fi
+          if [[ "${{ github.event.inputs['release-type'] }}" == "patch" ]]; then
+            echo "Patch release selected. Skipping build-version and build-number validation."
+          fi
+
   check-formatting:
     if: github.event_name == 'pull_request'
     uses: ./.github/workflows/shared-workflow.yaml
@@ -41,6 +64,7 @@ jobs:
       package-name: conferenceapp
 
   android-build:
+    needs: validate-inputs
     if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs['release-type'] == 'build' }}
     uses: ./.github/workflows/shared-workflow.yaml
     with:
@@ -54,6 +78,7 @@ jobs:
       FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
 
   ios-build:
+    needs: validate-inputs
     if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs['release-type'] == 'build' }}
     uses: ./.github/workflows/shared-workflow.yaml
     with:
@@ -71,6 +96,7 @@ jobs:
       SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
   
   patch-release:
+    needs: validate-inputs
     if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs['release-type'] == 'patch' }}
     uses: ./.github/workflows/shared-workflow.yaml
     with:
